apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: node-ci-cd
  name: node-ci-cd
spec:
  ports:
  - name: 80-3000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: node-ci-cd
  type: NodePort
status:
  loadBalancer: {}
